language: python
python:
  - '3.9'
before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE='disquaire_project.settings"

services:
  - postgresql
branches:
  only:
    - staging

script:
  - ./manage.py test
